export const sliderItems = [
  {
    id: 1,
    img: "https://i.ibb.co/gV4Knyx/summersale.webp",
    title: "SUMMER SALE",
    desc: "HEY CHECK OUT THIS EXCLUSIVE DEALS UPTO 70%,  DON'T MISS OUT ON THEM",
    bg: "f4c2c0",
  },
  {
    id: 2,
    img: "https://i.ibb.co/9g2brWr/automnsale.jpg",
    title: "AUTUMN LOVE",
    desc: "HEY CHECK OUT THIS EXCLUSIVE DEALS UPTO 50%,  DON'T MISS OUT ON THEM",
    bg: "feb902",
  },
  {
    id: 3,
    img: "https://i.ibb.co/Y0QF6G9/populardeal.webp",
    title: "POPULAR DEAL",
    desc: "HEY CHECK OUT THIS EXCLUSIVE DEALS UPTO 70%,  DON'T MISS OUT ON THEM",
    bg: "5f756d",
  },
];

export const categories = [
  {
    id: 1,
    img: "https://i.ibb.co/7zvyYZc/5ef27b49988ee34e43460cf4.jpg",
    title: "SHIRT STYLE",
    category: "men",
  },
  {
    id: 2,
    img: "https://i.ibb.co/WkXNHrm/longuewearstyle.jpg",
    title: "LOUNGEWEAR STYLE",
    category: "women",
  },
  {
    id: 3,
    img: "https://i.ibb.co/MS9YYS3/lightjacket.jpg",
    title: "LIGHT JACKETS",
    category: "jens",
  },
];

export const popularProducts = [
  {
    _id: "620fe1d7c2f59685b1eac7b0",
    title: "men's shirt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
    img: "https://i.ibb.co/Kjf7djk/popular1.webp",
    categories: ["tshirt", "men"],
    size: ["M", "l", "s", ""],
    color: ["grey", "red", "black"],
    price: 37,
    inStock: true,
    createdAt: { $date: { $numberLong: "1645208023354" } },
    updatedAt: { $date: { $numberLong: "1645208023354" } },
  },
  {
    _id: "620fe2d9c2f59685b1eac7b9",
    title: "mens shirt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
    img: "https://i.ibb.co/ySZn6Gj/popular2.webp",
    categories: ["tshirt", "men"],
    size: ["s"],
    color: ["black", "grey"],
    price: 37,
    inStock: true,
    createdAt: { $date: { $numberLong: "1645208281949" } },
    updatedAt: { $date: { $numberLong: "1645208281949" } },
  },
  {
    _id: "620fe32bc2f59685b1eac7bb",
    title: "women's long",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
    img: "https://i.ibb.co/rdM5hjb/popular3.webp",
    categories: ["longwear", "women"],
    size: ["s", "m", "l"],
    color: ["red"],
    price: 137,
    inStock: true,
    createdAt: { $date: { $numberLong: "1645208363329" } },
    updatedAt: { $date: { $numberLong: "1645208363329" } },
  },
  {
    _id: "620fe345c2f59685b1eac7bd",
    title: "mens hat",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
    img: "https://i.ibb.co/L5BbrzQ/popular4.webp",
    categories: ["hat", "men"],
    size: ["s", "xs", "l", "m", ""],
    color: ["brown", "red", "black"],
    price: 13,
    inStock: true,
    createdAt: { $date: { $numberLong: "1645208389688" } },
    updatedAt: { $date: { $numberLong: "1645208389688" } },
  },
  {
    _id: "620fe366c2f59685b1eac7bf",
    title: "women's coat",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
    img: "https://i.ibb.co/4pBfyst/popular5.webp",
    categories: ["coat", "women"],
    size: ["m"],
    color: ["brown"],
    price: 55,
    inStock: true,
    createdAt: { $date: { $numberLong: "1645208422608" } },
    updatedAt: { $date: { $numberLong: "1645208422608" } },
  },
  {
    _id: "620fe37dc2f59685b1eac7c1",
    title: "women's bag",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
    img: "https://i.ibb.co/XJJDY8W/popular6.webp",
    categories: ["bag", "women"],
    size: ["m"],
    color: ["brown"],
    price: 15,
    inStock: true,
    createdAt: { $date: { $numberLong: "1645208445286" } },
    updatedAt: { $date: { $numberLong: "1645208445286" } },
  },
  {
    _id: "620fe3a0c2f59685b1eac7c3",
    title: "women's jacket",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
    img: "https://i.ibb.co/dcf3b7H/popular7.webp",
    categories: ["jacket", "women"],
    size: ["m", "s", "l", ""],
    color: ["red", "brown", "grey", "black"],
    price: 30,
    inStock: true,
    createdAt: { $date: { $numberLong: "1645208480887" } },
    updatedAt: { $date: { $numberLong: "1645208480887" } },
  },
  {
    _id: "620fe3bac2f59685b1eac7c5",
    title: "women's longwear",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
    img: "https://i.ibb.co/m9bHq5f/popular8.webp",
    categories: ["jacket", "women"],
    size: ["l"],
    color: ["red"],
    price: 30,
    inStock: true,
    createdAt: { $date: { $numberLong: "1645208506710" } },
    updatedAt: { $date: { $numberLong: "1645208506710" } },
  },
];
